Repository shivamm-verma/Daily-DSA, pull requests merged in 2025-08, with the labels that each got.

#63 maximum sub array sum - Fixes #18
  10_maximum_subarray_sum/cpp_code.cpp
  10_maximum_subarray_sum/java_code.java
  10_maximum_subarray_sum/markdown.md
  10_maximum_subarray_sum/python_code.py
Labels: Level-2, GsSOC

#64 Kth smallest node in the BST
  13_Kth_Smallest_element_in_BST/Better/better_c++.cpp
  13_Kth_Smallest_element_in_BST/Better/better_java.java
  13_Kth_Smallest_element_in_BST/Better/better_python.py
  13_Kth_Smallest_element_in_BST/BruteForce/brute.cpp
  13_Kth_Smallest_element_in_BST/BruteForce/brute_java.java
  13_Kth_Smallest_element_in_BST/BruteForce/brute_python.py
  13_Kth_Smallest_element_in_BST/Optimal/Optimal_c++.cpp
  13_Kth_Smallest_element_in_BST/Optimal/Optimal_java.java
  13_Kth_Smallest_element_in_BST/Optimal/Optimal_python.py
  13_Kth_Smallest_element_in_BST/markdown.md
Labels: Level-3

#67 Adding file for Moore's Voting Algorithm
  16_Moore's-Voting-Algorithm/Markdown.md
  16_Moore's-Voting-Algorithm/code.cpp
  16_Moore's-Voting-Algorithm/java-code.java
  16_Moore's-Voting-Algorithm/python-code.py
Labels: Level-2

#65 Added files for Search in a Rotated Sorted Array
  14_Search_in_rotated_sorted_array/Better/Better_c++.cpp
  14_Search_in_rotated_sorted_array/Better/Better_java.java
  14_Search_in_rotated_sorted_array/Better/Better_python.py
  14_Search_in_rotated_sorted_array/Brute/Brute_c++.cpp
  14_Search_in_rotated_sorted_array/Brute/Brute_java.java
  14_Search_in_rotated_sorted_array/Brute/Brute_python.py
  14_Search_in_rotated_sorted_array/Optimal/Solution.cpp
  14_Search_in_rotated_sorted_array/Optimal/Solution_java.java
  14_Search_in_rotated_sorted_array/Optimal/Solution_python.py
  14_Search_in_rotated_sorted_array/markdown.md
Labels: Level-2

#81 Adding odd/even program
  17_Even_or_odd/C++_code.cpp
  17_Even_or_odd/Java_code.java
  17_Even_or_odd/Markdown.md
Labels: Level-2

#139 Trapping rainwater
  22_Smallest-Range-Covering-Elements-from-K-Lists/markdown.md
  23_Trapping_Rain_Water_II/cpp-code.cpp
  23_Trapping_Rain_Water_II/java-code.java
  23_Trapping_Rain_Water_II/markdown.md
  23_Trapping_Rain_Water_II/python-code.py
Labels: Requested Changes

#198 Levenshtein_Algorithm
  Dynamic Programming/Levenshtein_Algorithm_DP/Better (DP)/Better.cpp
  Dynamic Programming/Levenshtein_Algorithm_DP/Better (DP)/Better.java
  Dynamic Programming/Levenshtein_Algorithm_DP/Better (DP)/Better.py
  Dynamic Programming/Levenshtein_Algorithm_DP/Markdown.md
  Dynamic Programming/Levenshtein_Algorithm_DP/Optimal (Space Optimization)/Optimal.cpp
  Dynamic Programming/Levenshtein_Algorithm_DP/Optimal (Space Optimization)/Optimal.java
  Dynamic Programming/Levenshtein_Algorithm_DP/Optimal (Space Optimization)/Optimal.py
  Recursion and Backtracking/Levenshtein_Algorithm_Recursion/Brute_Force.cpp
  Recursion and Backtracking/Levenshtein_Algorithm_Recursion/Brute_Force.java
  Recursion and Backtracking/Levenshtein_Algorithm_Recursion/Brute_Force.py
  Recursion and Backtracking/Levenshtein_Algorithm_Recursion/Markdown.md
Labels: Requested Changes

#187 Sliding Window Maximum
  Sliding Window/Sliding Window Maximum/Brute/java code.java
  Sliding Window/Sliding Window Maximum/Brute/python code.py
  Sliding Window/Sliding Window Maximum/Markdown.md
  Sliding Window/Sliding Window Maximum/Optimal/java code.java
  Sliding Window/Sliding Window Maximum/Optimal/python code.py
Labels: Requested Changes, Inactive

#269 Added files for Longest Increasing path in the Matrix
  Matrix/Longest Increasing Path in a matrix/Better/Solution_c++.cpp
  Matrix/Longest Increasing Path in a matrix/Better/Solution_java.java
  Matrix/Longest Increasing Path in a matrix/Better/Solution_python.py
  Matrix/Longest Increasing Path in a matrix/BruteForce/Solution.cpp
  Matrix/Longest Increasing Path in a matrix/BruteForce/Solution_java.java
  Matrix/Longest Increasing Path in a matrix/BruteForce/Solution_python.py
  Matrix/Longest Increasing Path in a matrix/Optimized/Solution.cpp
  Matrix/Longest Increasing Path in a matrix/Optimized/Solution_java.java
  Matrix/Longest Increasing Path in a matrix/Optimized/Solution_python.py
  Matrix/Longest Increasing Path in a matrix/markdown.md
Labels: Requested Changes

#306 3Sum Closet
  Two Pointers/3Sum Closest/3sum.cpp
  Two Pointers/3Sum Closest/3sum.py
  Two Pointers/3Sum Closest/ThreeSumClosest.java
  Two Pointers/3Sum Closest/markdown.md
Labels: Requested Changes
